---
title: "Re-Analysis of Datasets"
author: "Tobias Fellinger"
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
format: 
  pdf: 
    latex_engine: lualatex
    fig-pos: 'ht'
    include-in-header: 
      text: |
        \let\oldsection\section
        \renewcommand\section{\clearpage\oldsection}
---

This short report contains the output of several analysis methods applied to the reconstructed individual participant data from the studies on Terifluomide, Nivolumab and Prembrolizumap with minimal annotations.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(message = FALSE)

library(SimNPH)
library(tidyverse)
library(rlang)
library(survival)
library(YPmodel)

# months to days
m2d <- \(t) 365.25*t/12
```

```{r read_data}
# files for IPD
ipd_files <- data.frame(
  file = c(
    "../data/ipd/506_time_to_relapse.Rdata",
    "../data/ipd/6481_os.Rdata",
    "../data/ipd/9883_os.Rdata"
  ),
  name = c(
    "Terifluomide",
    "Nivolumab",
    "Prembrolizumap"
  )
)

all_ipd_data <- lapply(split(ipd_files, 1:nrow(ipd_files)), \(i){
  load(i$file)
  names(all_patients) <- c("t", "evt", "trt")
  all_patients$evt <- as.logical(all_patients$evt)
  all_patients
})
names(all_ipd_data) <- ipd_files$name
```

```{r define_tests}
my_tests <- list(
  # tests
  pw_exp_3  = analyse_piecewise_exponential(cuts=seq(3, 240, by= 3), testing_only=TRUE),
  pw_exp_12 = analyse_piecewise_exponential(cuts=seq(12, 240, by=12), testing_only=TRUE),
  peto_peto = analyse_gehan_wilcoxon(alternative = "one.sided"),
  fh_0_0 = analyse_logrank_fh_weights(rho=0, gamma=0, alternative = "one.sided"),
  fh_0_1 = analyse_logrank_fh_weights(rho=0, gamma=1, alternative = "one.sided"),
  fh_1_0 = analyse_logrank_fh_weights(rho=1, gamma=0, alternative = "one.sided"),
  fh_1_1 = analyse_logrank_fh_weights(rho=1, gamma=1, alternative = "one.sided"),
  logrank = analyse_logrank(alternative = "one.sided"),
  max_combo = analyse_maxcombo(alternative = "one.sided"),
  modest_6 = analyse_modelstly_weighted(t_star=m2d(6)),
  modest_8 = analyse_modelstly_weighted(t_star=m2d(8))
)
```

```{r define_estimators}
my_estimators <- list(
  # estimation
  ahr_6m   = analyse_ahr(type="AHR", max_time=(6), alternative = "one.sided"),
  ahr_12m  = analyse_ahr(type="AHR", max_time=(12), alternative = "one.sided"),
  gahr_6m  = analyse_ahr(type="gAHR", max_time=(6), alternative = "one.sided"),
  gahr_12m = analyse_ahr(type="gAHR", max_time=(12), alternative = "one.sided"),
  median_surv = analyse_diff_median_survival(alternative = "one.sided"),
  milestone_6m = analyse_milestone_survival(times=(6), alternative = "one.sided"),
  milestone_12m = analyse_milestone_survival(times=(12), alternative = "one.sided"),
  rmst_diff_6m  = analyse_rmst_diff(max_time = (6), alternative = "one.sided"),
  rmst_diff_12m = analyse_rmst_diff(max_time = (12), alternative = "one.sided"),
  cox = analyse_coxph(alternative = "one.sided"),
  aft_weibull = analyse_aft(dist="weibull", alternative = "one.sided"),
  aft_lognormal = analyse_aft(dist="lognormal", alternative = "one.sided"),
  diff_med_weibull = analyse_weibull(alternative = "two.sided")
)

extract_results <- list(
  ahr_6m  = exprs(est=AHR, lower=AHR_lower, upper=AHR_upper, null=1),
  ahr_12m = exprs(est=AHR, lower=AHR_lower, upper=AHR_upper, null=1),
  gahr_6m  = exprs(est=gAHR, lower=gAHR_lower, upper=gAHR_upper, null=1),
  gahr_12m = exprs(est=gAHR, lower=gAHR_lower, upper=gAHR_upper, null=1),
  median_surv = exprs(est=diff_Q, lower=diff_Q_lower, upper=diff_Q_upper, null=0),
  milestone_6m = exprs(est=milestone_surv_ratio, lower=milestone_surv_ratio_lower, upper=milestone_surv_ratio_upper, null=1),
  milestone_12m = exprs(est=milestone_surv_ratio, lower=milestone_surv_ratio_lower, upper=milestone_surv_ratio_upper, null=1),
  rmst_diff_6m  = exprs(est=rmst_diff, lower=rmst_diff_lower, upper=rmst_diff_upper, null=0),
  rmst_diff_12m = exprs(est=rmst_diff, lower=rmst_diff_lower, upper=rmst_diff_upper, null=0),
  cox = exprs(est=hr, lower=hr_lower, upper=hr_upper, null=1),
  aft_weibull = exprs(est=coef, lower=lower, upper=upper, null=0),
  aft_lognormal = exprs(est=coef, lower=lower, upper=upper, null=0),
  diff_med_weibull = exprs(est=diff_med_est,lower=diff_med_lower, upper=diff_med_upper, null=0)
)

```

# Terifluomide

```{r}
study <- "Terifluomide"
ipd_data <- all_ipd_data[[study]]

# for time dependent coefficients
my_max <- 104
my_interval <- 3*(365.25/12)/7 # 3 months in weeks
my_breaks <- seq(0, my_max+my_interval, by=my_interval)
my_knots <- exp(seq(0, log(my_max), length.out=4))

# for plots:
ylim <- c(0, 2)
```

```{r, child="reanalysis_of_datasets_child.Qmd"}

```

# Nivolumab

```{r}
study <- "Nivolumab"
ipd_data <- all_ipd_data[[study]]

# for time dependent coefficients
my_max <- 29
my_interval <- 3
my_breaks <- seq(0, my_max+my_interval, by=my_interval)
my_knots <- exp(seq(0, log(my_max), length.out=4))

# for plots:
ylim <- c(0,2.5)
```

```{r, child="reanalysis_of_datasets_child.Qmd"}

```

# Prembrolizumap

```{r}
study <- "Prembrolizumap"
ipd_data <- all_ipd_data[[study]]

# for time dependent coefficients
my_max <- 41
my_interval <- 3
my_breaks <- seq(0, my_max+my_interval, by=my_interval)
my_knots <- exp(seq(0, log(my_max), length.out=4))

# for plots:
ylim <- c(0,2)
```

```{r, child="reanalysis_of_datasets_child.Qmd"}

```
